# Generated by Django 3.2.5 on 2021-07-23 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basketapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
    ]
